# Generated by Django 4.2.3 on 2023-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='discription',
        ),
    ]
