# Generated by Django 4.2.3 on 2023-10-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0002_rename_description_medicine_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='discription',
        ),
        migrations.AddField(
            model_name='medicine',
            name='available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
