# Generated by Django 4.2.3 on 2023-11-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0003_remove_medicine_discription_medicine_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
    ]
